<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('units', function (Blueprint $table) {
$table->integer('m2');
$table->string('modelo');
$table->string('rec');
$table->integer('baños');
$table->string('cajones');
$table->string('vista');
});
DB::table('units')->insert([
'unit' => '101',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2902845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '102',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2454444.441',
'status' => '1',
]);
DB::table('units')->insert([
'unit' => '103',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2738533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '104',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3745356.887',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '105',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3632431.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '106',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3160488.873',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '107',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3426822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '108',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3533355.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '109',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3077016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '110',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2454444.441',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '111',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2738533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '201',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2762533.332',
'status' => '1',
]);
DB::table('units')->insert([
'unit' => '202',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2521266.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '203',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2926845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '204',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3994078.3',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '205',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3874377.447',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '206',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3374118.206',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '207',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3656431.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '208',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3769356.887',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '209',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2926845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '210',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2671102.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '211',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2762533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '301',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2786533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '302',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2853928.826',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '303',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3309637.015',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '304',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4256282.998',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '305',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3898377.447',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '306',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3599125.298',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '307',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3474822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '308',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3581355.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '309',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2950845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '310',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2502444.441',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '311',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2786533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '401',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2810533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '402',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2526444.441',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '403',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3149016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '404',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3817356.887',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '405',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3704431.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '406',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3836192.816',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '407',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4153400.094',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '408',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3605355.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '409',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3333637.015',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '410',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2569266.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '411',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2810533.332',
'status' => '1',
]);
DB::table('units')->insert([
'unit' => '501',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3357637.015',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '502',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2743102.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '503',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2998845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '504',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4066078.3',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '505',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3522822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '506',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3446118.206',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '507',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3946377.447',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '508',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3841356.887',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '509',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2998845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '510',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2901928.826',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '511',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3173016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '601',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3022845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '602',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2617266.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '603',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3022845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '604',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4090078.3',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '605',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3546822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '606',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3280488.873',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '607',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3752431.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '608',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3653355.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '609',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3381637.015',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '610',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2767102.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '611',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3197016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '701',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2823000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '702',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2494000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '703',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2823000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '704',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3885200',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '705',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3772400',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '706',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3340000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '707',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3772400',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '708',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3885200',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '709',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2823000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '710',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2791102.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '711',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3405637.015',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '801',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2906533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '802',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2665266.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '803',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3245016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '804',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3913356.887',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '805',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3594822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '806',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3719125.298',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '807',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4018377.447',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '808',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4138078.3',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '809',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3070845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '810',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2973928.826',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '811',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3366758.862',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '901',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2930533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '902',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2839102.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '903',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3453637.015',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '904',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3725355.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '905',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3824431.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '906',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3542118.206',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '907',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3618822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '908',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4162078.3',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '909',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3269016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '910',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2646444.441',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '911',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3269016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1001',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2954533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1002',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2713266.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1003',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3118845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1004',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3961356.887',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1005',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4066377.447',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1006',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3376488.873',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1007',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3642822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1008',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4424282.998',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1009',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2954533.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1010',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2670444.441',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1011',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3293016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1101',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3501637.015',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1102',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3045928.826',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1103',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3317016.052',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1104',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3773355.554',
'status' => '1',
]);
DB::table('units')->insert([
'unit' => '1105',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3666822.22',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1106',
'm2' => '68',
'modelo' => 'AURA',
'rec' => '1',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4004192.816',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1107',
'm2' => '77.2',
'modelo' => 'LUA',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '3872431.554',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1108',
'm2' => '79.6',
'modelo' => 'LUA II',
'rec' => '2',
'baños' => '2',
'cajones' => '2 TANDEM ',
'vista' => 'SUR',
'price' => '4210078.3',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1109',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3142845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1110',
'm2' => '50',
'modelo' => 'LYRA',
'rec' => '1',
'baños' => '2',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '2887102.666',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1111',
'm2' => '57',
'modelo' => 'NOVA',
'rec' => '2',
'baños' => '1',
'cajones' => '1 SENCILLO ',
'vista' => 'NORTE INTERIOR',
'price' => '3142845.332',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '1',
'm2' => '57',
'modelo' => 'ROOF TOP 1',
'rec' => '',
'baños' => '1',
'cajones' => '',
'vista' => 'NORTE INTERIOR',
'price' => '855000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '2',
'm2' => '50',
'modelo' => 'ROOF TOP 2',
'rec' => '',
'baños' => '1',
'cajones' => '',
'vista' => 'NORTE INTERIOR',
'price' => '750000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '3',
'm2' => '57',
'modelo' => 'ROOF TOP 3',
'rec' => '',
'baños' => '1',
'cajones' => '',
'vista' => 'NORTE INTERIOR',
'price' => '855000',
'status' => '0',
]);
DB::table('units')->insert([
'unit' => '4',
'm2' => '79.6',
'modelo' => 'ROOF TOP 4',
'rec' => '',
'baños' => '1',
'cajones' => '',
'vista' => 'SUR',
'price' => '928401.45',
'status' => '1',
]);
DB::table('units')->insert([
'unit' => '5',
'm2' => '77.2',
'modelo' => 'ROOF TOP 5',
'rec' => '',
'baños' => '1',
'cajones' => '',
'vista' => 'SUR',
'price' => '1158000',
'status' => '0',
]);

    }
};